name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Check types with mypy
        run: hatch run types:check
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Install poppler
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install poppler-utils
      - name: Run tests
        run: hatch test --cover -py 3.9
